# Generated by Django 4.1.2 on 2022-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_permission_field_in_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
