# Generated by Django 4.1.2 on 2022-10-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_description_can_be_null_in_departments_and_vacancies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/%d/"),
        ),
    ]
