# Generated by Django 4.1.2 on 2022-11-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_type_of_photo_on_users"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteResume",
            new_name="FavouriteResume",
        ),
        migrations.RenameModel(
            old_name="FavoriteVacancy",
            new_name="FavouriteVacancy",
        ),
        migrations.AlterModelTable(
            name="favouriteresume",
            table="favourite_resumes",
        ),
        migrations.AlterModelTable(
            name="favouritevacancy",
            table="favourite_vacancies",
        ),
    ]
