# Generated by Django 4.1.2 on 2022-11-04 22:00
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_favorite_fields_to_favourite_in_users"),
    ]

    operations = []
