# Generated by Django 4.1.2 on 2022-11-04 22:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_activate_pg_trgm"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="resume",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["desired_job"], name="desired_job_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
