# Generated by Django 4.1.2 on 2022-11-04 22:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_activate_pg_trgm"),
    ]

    operations = [
    ]
