# Generated by Django 4.1.3 on 2022-11-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_added_desired_job_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="expected_experience",
            field=models.CharField(
                choices=[
                    ("no_experience", "No Experience"),
                    ("from_one_to_three_years", "From One To Three Years"),
                    ("from_three_to_six_years", "From Three To Six Years"),
                    ("more_than_six_years", "More Than Six Years"),
                ],
                max_length=32,
            ),
        ),
    ]
