# Generated by Django 4.1.3 on 2022-11-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_null_of_expected_experience_field_on_vacancies"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favouriteresume",
            unique_together={("user", "resume")},
        ),
        migrations.AlterUniqueTogether(
            name="favouritevacancy",
            unique_together={("user", "vacancy")},
        ),
    ]
