# Generated by Django 4.1.3 on 2022-11-08 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_added_unique_constraint_to_favourites_tables"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancyrequest",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="vacancyrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
