# Generated by Django 4.1.3 on 2022-11-21 08:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_updated_at_to_created_at_field_in_vacancies_requests"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="name_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"], name="description_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
