# Generated by Django 4.1.3 on 2022-11-21 08:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_updated_at_to_created_at_field_in_vacancies_requests"),
    ]

    operations = [
    ]
