# Generated by Django 4.1.3 on 2022-11-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_create_indexes_on_vacancies"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="resume",
            name="desired_job_idx",
        ),
        migrations.RemoveIndex(
            model_name="vacancy",
            name="name_idx",
        ),
        migrations.RemoveIndex(
            model_name="vacancy",
            name="description_idx",
        ),
    ]
