# Generated by Django 4.1.3 on 2022-11-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_create_indexes_on_vacancies"),
    ]

    operations = [
    ]
