# Generated by Django 4.1.3 on 2022-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_drop_all_indexes_on_resume_and_vacancy_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="desired_job",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="document",
            field=models.FileField(null=True, upload_to="resumes/%Y/%m/%d/"),
        ),
    ]
